openapi: 3.0.0
info:
  title: EVE-tools API
  varsion: 0.0.1

servers:
  - url: http://94.250.248.45:8080/
    description: Основной сервер разработки

paths:
  /regions:
    get:
      summary: Регионы вселенной EVE-online
      description: возвращает массив регионов
      tags:
        - regions
      responses:
        '200':
          description: JSON массив содержащий регоны вселенной
          content:
            'application/json':
              schema:
                type: array
                items :
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    constellations:
                      type: array
                      items:
                        type: integer
  /category:
    get:
      summary: Категории товаров во вселенной EVE-online
      description:
      tags:
        - categories
      parameters:
        - name: parent_id
          in: query
          required: false
          description: Id родительского каталога, для получения корневых групп, не указывайте параметр
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: ...
  /prices:
    get:
      summery: ...
      description: ...
      tags:
        - prices
      responses:
        '200':
          description: ...
  /prices/report:
    get:
      summery: ...
      description: ...
      tags:
        - prices
      responses:
        '200':
          description: ...